### ISSUE TITLE
vercel部署

### ISSUE THREAD

**Issue by 0x3st** [hyc-official/rainyun-auto-rewards#1]
大佬你好！我在部署的时候遇到了两个小问题

1. apikey是在Environment Variables添加一个环境变量 apikey = xxx就行了对吧？
2. 部署好后首页显示cannot GET / 是正常的吗？

**Comment by hyc1230** [comment]
> 大佬你好！我在部署的时候遇到了两个小问题
> 
> 1. apikey是在Environment Variables添加一个环境变量 apikey = xxx就行了对吧？
> 2. 部署好后首页显示cannot GET / 是正常的吗？

1. 是的。
2. 正常的，但是如果您有兴趣，也可以自己修改源代码，加上一个主页。

**Comment by hyc1230** [comment]
此 issue 将关闭，如果还有问题，欢迎继续追问或者新建 issue。
